security:
    encoders:
        App\Entity\User\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: security_logout
    access_control:
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_TECH: [ROLE_EVPT, ROLE_ADMIN, ROLE_ORGANISER, ROLE_EDITOR]
        ROLE_EVPT: [ROLE_ADMIN, ROLE_ORGANISER, ROLE_EDITOR]
        ROLE_ORGANISER: ROLE_ADMIN
        ROLE_EDITOR: ROLE_ADMIN
