twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        uploads_directory: '%uploads_directory%'
        sections: '%sections%'
        categories: '%news_categories%'
        countries: '%countries%'
        paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
