# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

    uploads_directory: '%kernel.project_dir%/uploads/'

    section_ids: about|conferences|hs|scholarship|members
    sections:
        about: About
        conferences: Conferences
        hs: Hume Studies
        scholarship: Scholarship
        members: Members

    page_template_ids: default|society-governance|conferences-forthcoming|conferences-all|hs-issues-archive|parallel-references|news-members|news-conferences|news-fellowships|news-archived|membership-stats|membership-list|minutes-reports|committee-voting
    page_templates:
        default: Default
        society-governance: Society Governance
        conferences-forthcoming: Forthcoming Conferences
        conferences-all: All Conferences
        hs-issues-archive: Hume Studies Issues Archive
        parallel-references: Parallel References Guide
        news-members: Members News
        news-conferences: Conference News
        news-fellowships: Fellowships and Awards News
        news-archived: Archived News
        membership-stats: Membership Statistics
        membership-list: List of Current Members
        minutes-reports: Society Minutes and Reports
        committee-voting: Commitee Voting Form

    society_email_template_ids: welcome|reminder
    society_email_templates:
        welcome:
            title: Welcome
            description: The welcome email is sent out to each individual as soon as they complete their registration on the site (and pay their dues through PayPal).
        reminder:
            title: Dues Reminder
            description: The dues reminder email is sent out to every member at the start of the month when their subscription is due (i.e. 1st June or 1st December).

    conference_email_template_ids: submission|review|thanks|accept|reject
    conference_email_templates:
        submission:
            title: Submission Acknowledgement
            description: The submission acknowledgement email is sent out to a user when they submit a paper for the Hume Conference.
        review:
            title: Review Invitation
            description: The review invitation email is sent out to someone you invite to review a paper.
        thanks:
            title: Review Acknowledgement
            description: The review acknowledgement email is sent out to a reviewer when they have submitted their review.
        accept:
            title: Submission Acceptance
            description: The acceptance email is sent out to a user when you accept their paper.
        reject:
            title: Submission Rejection
            description: The rejection email is sent out to a user when you reject their paper.

    news_category_ids: society|members|conferences|fellowships
    news_categories:
        society: Society News
        members: Members News
        conferences: Other Conferences
        fellowships: Fellowships and Awards

    conference_text_ids: submission
    conference_texts:
        submission:
            title: Submission Guidance
            description: The submission guidance text is shown directly above the submission form.

    countries:
        AFG: Afghanistan
        ALA: Åland Islands
        ALB: Albania
        DZA: Algeria
        ASM: American Samoa
        AND: Andorra
        AGO: Angola
        AIA: Anguilla
        ATA: Antarctica
        ATG: Antigua and Barbuda
        ARG: Argentina
        ARM: Armenia
        ABW: Aruba
        AUS: Australia
        AUT: Austria
        AZE: Azerbaijan
        BHS: Bahamas
        BHR: Bahrain
        BGD: Bangladesh
        BRB: Barbados
        BLR: Belarus
        BEL: Belgium
        BLZ: Belize
        BEN: Benin
        BMU: Bermuda
        BTN: Bhutan
        BOL: Bolivia
        BES: Bonaire, Sint Eustatius and Saba
        BIH: Bosnia and Herzegovina
        BWA: Botswana
        BVT: Bouvet Island
        BRA: Brazil
        IOT: British Indian Ocean Territory
        BRN: Brunei Darussalam
        BGR: Bulgaria
        BFA: Burkina Faso
        BDI: Burundi
        CPV: Cabo Verde
        KHM: Cambodia
        CMR: Cameroon
        CAN: Canada
        CYM: Cayman Islands
        CAF: Central African Republic
        TCD: Chad
        CHL: Chile
        CHN: China
        CXR: Christmas Island
        CCK: Cocos (Keeling) Islands
        COL: Colombia
        COM: Comoros
        COD: Democratic Republic of the Congo
        COG: Congo
        COK: Cook Islands
        CRI: Costa Rica
        CIV: Côte d'Ivoire
        HRV: Croatia
        CUB: Cuba
        CUW: Curaçao
        CYP: Cyprus
        CZE: Czechia
        DNK: Denmark
        DJI: Djibouti
        DMA: Dominica
        DOM: Dominican Republic
        ECU: Ecuador
        EGY: Egypt
        SLV: El Salvador
        GNQ: Equatorial Guinea
        ERI: Eritrea
        EST: Estonia
        SWZ: Eswatini
        ETH: Ethiopia
        FLK: Falkland Islands
        FRO: Faroe Islands
        FJI: Fiji
        FIN: Finland
        FRA: France
        GUF: French Guiana
        PYF: French Polynesia
        ATF: French Southern Territories
        GAB: Gabon
        GMB: Gambia
        GEO: Georgia
        DEU: Germany
        GHA: Ghana
        GIB: Gibraltar
        GRC: Greece
        GRL: Greenland
        GRD: Grenada
        GLP: Guadeloupe
        GUM: Guam
        GTM: Guatemala
        GGY: Guernsey
        GIN: Guinea
        GNB: Guinea-Bissau
        GUY: Guyana
        HTI: Haiti
        HMD: Heard Island and McDonald Islands
        VAT: Holy See
        HND: Honduras
        HKG: Hong Kong
        HUN: Hungary
        ISL: Iceland
        IND: India
        IDN: Indonesia
        IRN: Iran
        IRQ: Iraq
        IRL: Ireland
        IMN: Isle of Man
        ISR: Israel
        ITA: Italy
        JAM: Jamaica
        JPN: Japan
        JEY: Jersey
        JOR: Jordan
        KAZ: Kazakhstan
        KEN: Kenya
        KIR: Kiribati
        PRK: Democratic People's Republic of Korea
        KOR: Republic of Korea
        KWT: Kuwait
        KGZ: Kyrgyzstan
        LAO: Lao People's Democratic Republic
        LVA: Latvia
        LBN: Lebanon
        LSO: Lesotho
        LBR: Liberia
        LBY: Libya
        LIE: Liechtenstein
        LTU: Lithuania
        LUX: Luxembourg
        MAC: Macao
        MKD: Macedonia
        MDG: Madagascar
        MWI: Malawi
        MYS: Malaysia
        MDV: Maldives
        MLI: Mali
        MLT: Malta
        MHL: Marshall Islands
        MTQ: Martinique
        MRT: Mauritania
        MUS: Mauritius
        MYT: Mayotte
        MEX: Mexico
        FSM: Micronesia
        MDA: Moldova
        MCO: Monaco
        MNG: Mongolia
        MNE: Montenegro
        MSR: Montserrat
        MAR: Morocco
        MOZ: Mozambique
        MMR: Myanmar
        NAM: Namibia
        NRU: Nauru
        NPL: Nepal
        NLD: Netherlands
        NCL: New Caledonia
        NZL: New Zealand
        NIC: Nicaragua
        NER: Niger
        NGA: Nigeria
        NIU: Niue
        NFK: Norfolk Island
        MNP: Northern Mariana Islands
        NOR: Norway
        OMN: Oman
        PAK: Pakistan
        PLW: Palau
        PSE: Palestine
        PAN: Panama
        PNG: Papua New Guinea
        PRY: Paraguay
        PER: Peru
        PHL: Philippines
        PCN: Pitcairn
        POL: Poland
        PRT: Portugal
        PRI: Puerto Rico
        QAT: Qatar
        REU: Réunion
        ROU: Romania
        RUS: Russian Federation
        RWA: Rwanda
        BLM: Saint Barthélemy
        SHN: Saint Helena, Ascension and Tristan da Cunha
        KNA: Saint Kitts and Nevis
        LCA: Saint Lucia
        MAF: Saint Martin (French part)
        SPM: Saint Pierre and Miquelon
        VCT: Saint Vincent and the Grenadines
        WSM: Samoa
        SMR: San Marino
        STP: Sao Tome and Principe
        SAU: Saudi Arabia
        SEN: Senegal
        SRB: Serbia
        SYC: Seychelles
        SLE: Sierra Leone
        SGP: Singapore
        SXM: Sint Maarten (Dutch part)
        SVK: Slovakia
        SVN: Slovenia
        SLB: Solomon Islands
        SOM: Somalia
        ZAF: South Africa
        SGS: South Georgia and the South Sandwich Islands
        SSD: South Sudan
        ESP: Spain
        LKA: Sri Lanka
        SDN: Sudan
        SUR: Suriname
        SJM: Svalbard and Jan Mayen
        SWE: Sweden
        CHE: Switzerland
        SYR: Syrian Arab Republic
        TWN: Taiwan
        TJK: Tajikistan
        TZA: Tanzania
        THA: Thailand
        TLS: Timor-Leste
        TGO: Togo
        TKL: Tokelau
        TON: Tonga
        TTO: Trinidad and Tobago
        TUN: Tunisia
        TUR: Turkey
        TKM: Turkmenistan
        TCA: Turks and Caicos Islands
        TUV: Tuvalu
        UGA: Uganda
        UKR: Ukraine
        ARE: United Arab Emirates
        GBR: United Kingdom
        UMI: United States Minor Outlying Islands
        USA: United States
        URY: Uruguay
        UZB: Uzbekistan
        VUT: Vanuatu
        VEN: Venezuela
        VNM: Viet Nam
        VGB: Virgin Islands (British)
        VIR: Virgin Islands (U.S.)
        WLF: Wallis and Futuna
        ESH: Western Sahara
        YEM: Yemen
        ZMB: Zambia
        ZWE: Zimbabwe
    regions:
        AFG: Asia
        ALA: Europe
        ALB: Europe
        DZA: Africa
        ASM: Oceania
        AND: Europe
        AGO: Africa
        AIA: Americas
        ATA: none
        ATG: Americas
        ARG: Americas
        ARM: Asia
        ABW: Americas
        AUS: Oceania
        AUT: Europe
        AZE: Asia
        BHS: Americas
        BHR: Asia
        BGD: Asia
        BRB: Americas
        BLR: Europe
        BEL: Europe
        BLZ: Americas
        BEN: Africa
        BMU: Americas
        BTN: Asia
        BOL: Americas
        BES: Americas
        BIH: Europe
        BWA: Africa
        BVT: Americas
        BRA: Americas
        IOT: Africa
        BRN: Asia
        BGR: Europe
        BFA: Africa
        BDI: Africa
        CPV: Africa
        KHM: Asia
        CMR: Africa
        CAN: Americas
        CYM: Americas
        CAF: Africa
        TCD: Africa
        CHL: Americas
        CHN: Asia
        CXR: Oceania
        CCK: Oceania
        COL: Americas
        COM: Africa
        COG: Africa
        COD: Africa
        COK: Oceania
        CRI: Americas
        CIV: Africa
        HRV: Europe
        CUB: Americas
        CUW: Americas
        CYP: Asia
        CZE: Europe
        DNK: Europe
        DJI: Africa
        DMA: Americas
        DOM: Americas
        ECU: Americas
        EGY: Africa
        SLV: Americas
        GNQ: Africa
        ERI: Africa
        EST: Europe
        SWZ: Africa
        ETH: Africa
        FLK: Americas
        FRO: Europe
        FJI: Oceania
        FIN: Europe
        FRA: Europe
        GUF: Americas
        PYF: Oceania
        ATF: Africa
        GAB: Africa
        GMB: Africa
        GEO: Asia
        DEU: Europe
        GHA: Africa
        GIB: Europe
        GRC: Europe
        GRL: Americas
        GRD: Americas
        GLP: Americas
        GUM: Oceania
        GTM: Americas
        GGY: Europe
        GIN: Africa
        GNB: Africa
        GUY: Americas
        HTI: Americas
        HMD: Oceania
        VAT: Europe
        HND: Americas
        HKG: Asia
        HUN: Europe
        ISL: Europe
        IND: Asia
        IDN: Asia
        IRN: Asia
        IRQ: Asia
        IRL: Europe
        IMN: Europe
        ISR: Asia
        ITA: Europe
        JAM: Americas
        JPN: Asia
        JEY: Europe
        JOR: Asia
        KAZ: Asia
        KEN: Africa
        KIR: Oceania
        PRK: Asia
        KOR: Asia
        KWT: Asia
        KGZ: Asia
        LAO: Asia
        LVA: Europe
        LBN: Asia
        LSO: Africa
        LBR: Africa
        LBY: Africa
        LIE: Europe
        LTU: Europe
        LUX: Europe
        MAC: Asia
        MKD: Europe
        MDG: Africa
        MWI: Africa
        MYS: Asia
        MDV: Asia
        MLI: Africa
        MLT: Europe
        MHL: Oceania
        MTQ: Americas
        MRT: Africa
        MUS: Africa
        MYT: Africa
        MEX: Americas
        FSM: Oceania
        MDA: Europe
        MCO: Europe
        MNG: Asia
        MNE: Europe
        MSR: Americas
        MAR: Africa
        MOZ: Africa
        MMR: Asia
        NAM: Africa
        NRU: Oceania
        NPL: Asia
        NLD: Europe
        NCL: Oceania
        NZL: Oceania
        NIC: Americas
        NER: Africa
        NGA: Africa
        NIU: Oceania
        NFK: Oceania
        MNP: Oceania
        NOR: Europe
        OMN: Asia
        PAK: Asia
        PLW: Oceania
        PSE: Asia
        PAN: Americas
        PNG: Oceania
        PRY: Americas
        PER: Americas
        PHL: Asia
        PCN: Oceania
        POL: Europe
        PRT: Europe
        PRI: Americas
        QAT: Asia
        REU: Africa
        ROU: Europe
        RUS: Europe
        RWA: Africa
        BLM: Americas
        SHN: Africa
        KNA: Americas
        LCA: Americas
        MAF: Americas
        SPM: Americas
        VCT: Americas
        WSM: Oceania
        SMR: Europe
        STP: Africa
        SAU: Asia
        SEN: Africa
        SRB: Europe
        SYC: Africa
        SLE: Africa
        SGP: Asia
        SXM: Americas
        SVK: Europe
        SVN: Europe
        SLB: Oceania
        SOM: Africa
        ZAF: Africa
        SGS: Americas
        SSD: Africa
        ESP: Europe
        LKA: Asia
        SDN: Africa
        SUR: Americas
        SJM: Europe
        SWE: Europe
        CHE: Europe
        SYR: Asia
        TWN: Asia
        TJK: Asia
        TZA: Africa
        THA: Asia
        TLS: Asia
        TGO: Africa
        TKL: Oceania
        TON: Oceania
        TTO: Americas
        TUN: Africa
        TUR: Asia
        TKM: Asia
        TCA: Americas
        TUV: Oceania
        UGA: Africa
        UKR: Europe
        ARE: Asia
        GBR: Europe
        USA: Americas
        UMI: Oceania
        URY: Americas
        UZB: Asia
        VUT: Oceania
        VEN: Americas
        VNM: Asia
        VGB: Americas
        VIR: Americas
        WLF: Oceania
        ESH: Africa
        YEM: Asia
        ZMB: Africa
        ZWE: Africa

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
